apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::730788221910:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-DA1ILH3O97D3
      username: system:node:{{EC2PrivateDNSName}}
      - system:masters
      rolearn: arn:aws:iam::730788221910:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-06-27T01:42:18Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1499"
  uid: 902fe805-fd18-4fee-a7da-eecccb09e5d6
